package org.nandayo.dapi.editor.annotation;

import org.bukkit.Material;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Optionally placed on an Enum type (or on the field itself) to customize how
 * each constant appears in the choice-picker submenu generated by EnumFieldHandler.
 * <br>
 * If absent, the handler falls back to the constant's name() and Material.PAPER.
 * <pre>
 * Example — on the enum class itself:
 *
 *  {@literal @EditableOptions}(values = {
 *      {@literal @EditableOptions.Option}(constant = "KILLS", label = "Kill Count", icon = Material.DIAMOND_SWORD),
 *      {@literal @EditableOptions.Option}(constant = "SURVIVAL", label = "Last Alive", icon = Material.SHIELD),
 *   })
 *   public enum WinCondition { KILLS, SURVIVAL }
 * </pre>
 * <pre>
 * Example — on the field (overrides enum-level annotation for that field only):
 *
 *  {@literal @EditableField}(label = "Win Condition", icon = Material.GOLD_INGOT)
 *  {@literal @EditableOptions}(values = {
 *      {@literal @EditableOptions.Option}(constant = "KILLS", label = "Kill Count", icon = Material.DIAMOND_SWORD)
 *   })
 *   private WinCondition winCondition;
 * </pre>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.FIELD})
public @interface EditableOptions {

    Option[] values();

    @Retention(RetentionPolicy.RUNTIME)
    @Target({})          // only used as a nested annotation, not applied directly
    @interface Option {
        /** Exact name of the enum constant this option describes. */
        String constant();

        /** Display name shown on the item. */
        String label() default "";

        /** Icon for this enum constant. */
        Material icon() default Material.PAPER;

        /** Optional lore lines. */
        String[] description() default {};
    }
}
